namespace bnet.protocol.Types
{
	public enum InvitationRemovedReason
	{
		INVITATION_REMOVED_REASON_ACCEPTED,
		INVITATION_REMOVED_REASON_DECLINED,
		INVITATION_REMOVED_REASON_REVOKED,
		INVITATION_REMOVED_REASON_IGNORED,
		INVITATION_REMOVED_REASON_EXPIRED,
		INVITATION_REMOVED_REASON_CANCELED
	}
}
