namespace bnet.protocol.Types
{
	public enum SuggestionRemovedReason
	{
		SUGGESTION_REMOVED_REASON_APPROVED,
		SUGGESTION_REMOVED_REASON_DECLINED,
		SUGGESTION_REMOVED_REASON_EXPIRED,
		SUGGESTION_REMOVED_REASON_CANCELED
	}
}
