namespace bnet.protocol.report.v2.Types
{
	public enum UserSource
	{
		USER_SOURCE_OTHER,
		USER_SOURCE_WHISPER,
		USER_SOURCE_PROFILE,
		USER_SOURCE_BATTLE_TAG,
		USER_SOURCE_CHAT,
		USER_SOURCE_FRIEND_INVITATION,
		USER_SOURCE_VOICE
	}
}
