namespace bnet.protocol.games.v1.Types
{
	public enum GameEndedReason
	{
		GAME_ENDED_REASON_DISSOLVED_BY_GAME_SERVER,
		GAME_ENDED_REASON_DISSOLVED_BY_SERVICE,
		GAME_ENDED_REASON_DISSOLVED_BY_PLAYER,
		GAME_ENDED_REASON_DISSOLVED_BY_GAME_SERVER_DISCONNECT,
		GAME_ENDED_REASON_UNKNOWN,
		GAME_ENDED_REASON_GAME_MASTER_DISCONNECT
	}
}
