namespace Blizzard.Commerce
{
	public enum blz_commerce_scene_type_t
	{
		BLZ_COMMERCE_SCENE_BUFFER_UPDATE = 1,
		BLZ_COMMERCE_SCENE_EXTERNAL_LINK,
		BLZ_COMMERCE_SCENE_WINDOW_CLOSE_REQUEST,
		BLZ_COMMERCE_SCENE_READY,
		BLZ_COMMERCE_SCENE_DISCONNECT,
		BLZ_COMMERCE_SCENE_CANCEL,
		BLZ_COMMERCE_SCENE_WINDOW_RESIZE,
		BLZ_COMMERCE_SCENE_CURSOR_CHANGE,
		BLZ_COMMERCE_SCENE_CLOSE_REQUESTED,
		BLZ_COMMERCE_SCENE_WINDOW_RESIZE_REQUESTED,
		BLZ_COMMERCE_SCENE_CLOSE,
		BLZ_SCENE_IME_COMPOSITION_RANGE_CHANGED,
		BLZ_SCENE_IME_STATE_CHANGED,
		BLZ_SCENE_IME_COMPOSITION_CANCELED,
		BLZ_SCENE_IME_TEXT_SELECTION_CHANGED,
		BLZ_SCENE_IME_TEXT_BOUNDS_CHANGED
	}
}
