namespace Blizzard.Commerce
{
	public enum scene_ime_input_type_t
	{
		IME_TYPE_NONE,
		IME_TYPE_TEXT,
		IME_TYPE_PASSWORD,
		IME_TYPE_SEARCH,
		IME_TYPE_EMAIL,
		IME_TYPE_NUMBER,
		IME_TYPE_TELEPHONE,
		IME_TYPE_URL,
		IME_TYPE_DATE,
		IME_TYPE_DATE_TIME,
		IME_TYPE_DATE_TIME_LOCAL,
		IME_TYPE_MONTH,
		IME_TYPE_TIME,
		IME_TYPE_WEEK,
		IME_TYPE_TEXT_AREA,
		IME_TYPE_CONTENT_EDITABLE,
		IME_TYPE_DATE_TIME_FIELD
	}
}
