namespace PegasusShared
{
	public enum AchieveRemoveReason
	{
		ACHIEVE_REMOVE_REASON_UNKNOWN,
		ACHIEVE_REMOVE_REASON_PLAYER_CANCEL,
		ACHIEVE_REMOVE_REASON_QUEST_ACTIVATE_WHEN_FULL,
		ACHIEVE_REMOVE_REASON_RETURNING_PLAYER_ACTIVATE,
		ACHIEVE_REMOVE_REASON_RETURNING_PLAYER_OPTOUT
	}
}
