namespace PegasusShared
{
	public enum AssetType
	{
		ASSET_TYPE_SCENARIO = 1,
		ASSET_TYPE_SUBSET_CARD,
		ASSET_TYPE_DECK_RULESET,
		ASSET_TYPE_REWARD_CHEST,
		ASSET_TYPE_GUEST_HEROES,
		ASSET_TYPE_DECK_TEMPLATE
	}
}
