namespace PegasusShared
{
	public enum BlizzardCheckoutStatus
	{
		BLIZZARD_CHECKOUT_STATUS_START = 1,
		BLIZZARD_CHECKOUT_STATUS_CANCELED,
		BLIZZARD_CHECKOUT_STATUS_COMPLETED_FAILED,
		BLIZZARD_CHECKOUT_STATUS_COMPLETED_SUCCESS
	}
}
