namespace PegasusShared
{
	public enum BnetGameType
	{
		BGT_UNKNOWN = 0,
		BGT_FRIENDS = 1,
		BGT_RANKED_STANDARD = 2,
		BGT_ARENA = 3,
		BGT_VS_AI = 4,
		BGT_TUTORIAL = 5,
		BGT_ASYNC = 6,
		BGT_CASUAL_STANDARD = 10,
		BGT_TEST1 = 11,
		BGT_TEST2 = 12,
		BGT_TEST3 = 13,
		BGT_TAVERNBRAWL_PVP = 0x10,
		BGT_TAVERNBRAWL_1P_VERSUS_AI = 17,
		BGT_TAVERNBRAWL_2P_COOP = 18,
		BGT_RANKED_WILD = 30,
		BGT_CASUAL_WILD = 0x1F,
		BGT_FSG_BRAWL_VS_FRIEND = 40,
		BGT_FSG_BRAWL_PVP = 41,
		BGT_FSG_BRAWL_1P_VERSUS_AI = 42,
		BGT_FSG_BRAWL_2P_COOP = 43,
		BGT_RANKED_STANDARD_NEW_PLAYER = 45,
		BGT_BATTLEGROUNDS = 50,
		BGT_BATTLEGROUNDS_FRIENDLY = 51,
		BGT_PVPDR_PAID = 54,
		BGT_PVPDR = 55,
		BGT_RESERVED_18_22 = 56,
		BGT_RESERVED_18_23 = 57,
		BGT_RANKED_CLASSIC = 58,
		BGT_CASUAL_CLASSIC = 59,
		BGT_LAST = 60
	}
}
