namespace PegasusShared
{
	public enum DeckSourceType
	{
		DECK_SOURCE_TYPE_UNKNOWN,
		DECK_SOURCE_TYPE_NORMAL,
		DECK_SOURCE_TYPE_TEMPLATE,
		DECK_SOURCE_TYPE_BASIC_DECK,
		DECK_SOURCE_TYPE_INNKEEPER_DECK,
		DECK_SOURCE_TYPE_PASTED_DECK
	}
}
