namespace PegasusShared
{
	public enum GameSaveOwnerType
	{
		GAME_SAVE_OWNER_TYPE_UNKNOWN = 0,
		GAME_SAVE_OWNER_TYPE_PLAYER = 1,
		GAME_SAVE_OWNER_TYPE_FIRESIDE_GATHERING = 2,
		GAME_SAVE_OWNER_TYPE_COUNT = 3,
		GAME_SAVE_OWNER_TYPE_FIRST = 1
	}
}
