namespace PegasusShared
{
	public enum RecruitAFriendState
	{
		RAF_RECRUITABLE = 1,
		RAF_RECRUITED = 2,
		RAF_GRADUATED = 3,
		RAF_VALEDICTORIAN = 4,
		RAF_NOT_RECRUITABLE_WRONG_REGION = 1000,
		RAF_NOT_RECRUITABLE_TOO_OLD = 1001,
		RAF_GRADUATED_WITHOUT_RECRUITER = 1002
	}
}
