public enum AchievementDbId
{
	INVALID = 0,
	FIRST_BLOOD = 11,
	ENTER_THE_ARENA = 56,
	RETURNING_PLAYER_QUEST1 = 568,
	RETURNING_PLAYER_QUEST2 = 569,
	RETURNING_PLAYER_QUEST3 = 571,
	FROSTMOURNE_MASTER_ACHIEVE = 768
}
