public enum ClassUnlockAchieveIds
{
	ACHIEVE_ID_UNLOCK_DRUID = 1,
	ACHIEVE_ID_UNLOCK_HUNTER = 2,
	ACHIEVE_ID_UNLOCK_MAGE = 3,
	ACHIEVE_ID_UNLOCK_PALADIN = 4,
	ACHIEVE_ID_UNLOCK_PRIEST = 5,
	ACHIEVE_ID_UNLOCK_ROGUE = 6,
	ACHIEVE_ID_UNLOCK_SHAMAN = 7,
	ACHIEVE_ID_UNLOCK_WARLOCK = 8,
	ACHIEVE_ID_UNLOCK_WARRIOR = 9,
	ACHIEVE_ID_UNLOCK_DEMONHUNTER = 2598
}
