public enum MobilePermission
{
	INVALID,
	COARSE_LOCATION,
	FINE_LOCATION,
	BEACON,
	WIFI,
	MICROPHONE,
	CAMERA,
	BLUETOOTH,
	NFC,
	READ_EXTERNAL_STORAGE,
	WRITE_EXTERNAL_STORAGE,
	READ_PHONE_STATE,
	GOOGLE_PUSH_NOTIFICATIONS,
	AMAZON_PUSH_NOTIFICATIONS,
	GOOGLE_DRIVE
}
