using System.ComponentModel;

public enum Option
{
	INVALID,
	[Description("clientOptionsVersion")]
	CLIENT_OPTIONS_VERSION,
	[Description("sound")]
	SOUND,
	[Description("music")]
	MUSIC,
	[Description("cursor")]
	CURSOR,
	[Description("hud")]
	HUD,
	[Description("streaming")]
	STREAMING,
	[Description("soundvolume")]
	SOUND_VOLUME,
	[Description("musicvolume")]
	MUSIC_VOLUME,
	[Description("graphicswidth")]
	GFX_WIDTH,
	[Description("graphicsheight")]
	GFX_HEIGHT,
	[Description("graphicsfullscreen")]
	GFX_FULLSCREEN,
	[Description("hasseennewcinematic")]
	HAS_SEEN_NEW_CINEMATIC,
	[Description("graphicsquality")]
	GFX_QUALITY,
	[Description("fakepackopening")]
	FAKE_PACK_OPENING,
	[Description("fakepackcount")]
	FAKE_PACK_COUNT,
	[Description("healthygamingdebug")]
	HEALTHY_GAMING_DEBUG,
	[Description("laststate")]
	LAST_SCENE_MODE,
	[Description("locale")]
	LOCALE,
	[Description("idlekicker")]
	IDLE_KICKER,
	[Description("idlekicktime")]
	IDLE_KICK_TIME,
	[Description("backgroundsound")]
	BACKGROUND_SOUND,
	[Description("preferredregion")]
	PREFERRED_REGION,
	[Description("forceShowIks")]
	FORCE_SHOW_IKS,
	[Description("peguidebug")]
	PEGUI_DEBUG,
	[Description("nearbyplayers2")]
	NEARBY_PLAYERS,
	[Description("wincameraclear")]
	GFX_WIN_CAMERA_CLEAR,
	[Description("msaa")]
	GFX_MSAA,
	[Description("fxaa")]
	GFX_FXAA,
	[Description("targetframerate")]
	GFX_TARGET_FRAME_RATE,
	[Description("vsync")]
	GFX_VSYNC,
	[Description("cardback")]
	CARD_BACK,
	[Description("cardback2")]
	CARD_BACK2,
	[Description("localtutorialprogress")]
	LOCAL_TUTORIAL_PROGRESS,
	[Description("connecttobnet")]
	CONNECT_TO_AURORA,
	[Description("reconnect")]
	RECONNECT,
	[Description("reconnectTimeout")]
	RECONNECT_TIMEOUT,
	[Description("reconnectRetryTime")]
	RECONNECT_RETRY_TIME,
	[Description("changedcardsdata")]
	CHANGED_CARDS_DATA,
	[Description("kelthuzadtaunts")]
	KELTHUZADTAUNTS,
	[Description("winposx")]
	GFX_WIN_POSX,
	[Description("winposy")]
	GFX_WIN_POSY,
	[Description("preferredcdnindex")]
	PREFERRED_CDN_INDEX,
	[Description("lastfaileddopversion")]
	LAST_FAILED_DOP_VERSION,
	[Description("touchmode")]
	TOUCH_MODE,
	[Description("gfxdevicewarning")]
	SHOWN_GFX_DEVICE_WARNING,
	[Description("intro")]
	INTRO,
	[Description("disableloginpopups")]
	DISABLE_LOGIN_POPUPS,
	[Description("tutoriallostprogress")]
	TUTORIAL_LOST_PROGRESS,
	[Description("errorScreen")]
	ERROR_SCREEN,
	[Description("innkeepersSpecialViews")]
	IKS_VIEW_ATTEMPTS,
	[Description("innkeepersSpecialLastDownloadTime")]
	IKS_LAST_DOWNLOAD_TIME,
	[Description("innkeepersSpecialLastResponse")]
	IKS_LAST_DOWNLOAD_RESPONSE,
	[Description("innkeepersSpecialCacheAge")]
	IKS_CACHE_AGE,
	[Description("innkeepersSpecialLastStoredResponse")]
	IKS_LAST_STORED_RESPONSE,
	[Description("cheatHistory")]
	CHEAT_HISTORY,
	[Description("preloadCardAssets")]
	PRELOAD_CARD_ASSETS,
	[Description("collectionPremiumType")]
	COLLECTION_PREMIUM_TYPE,
	[Description("devTimescale")]
	DEV_TIMESCALE,
	[Description("innkeepersSpecialLastShownAd")]
	IKS_LAST_SHOWN_AD,
	[Description("seenPackProductList")]
	SEEN_PACK_PRODUCT_LIST,
	[Description("showStandardOnly")]
	SHOW_STANDARD_ONLY,
	[Description("disableSetRotationIntro")]
	DISABLE_SET_ROTATION_INTRO,
	[Description("skipallmulligans")]
	SKIP_ALL_MULLIGANS,
	[Description("isTemporaryAccountCheat")]
	IS_TEMPORARY_ACCOUNT_CHEAT,
	[Description("temporaryAccountData")]
	TEMPORARY_ACCOUNT_DATA,
	[Description("disallowedCloudStorage")]
	DISALLOWED_CLOUD_STORAGE,
	[Description("createdAccount")]
	CREATED_ACCOUNT,
	[Description("lastEventHealUpDate")]
	LAST_HEAL_UP_EVENT_DATE,
	[Description("pushNotificationStatus")]
	PUSH_NOTIFICATION_STATUS,
	[Description("dbfXmlLoading")]
	DBF_XML_LOADING,
	[Description("hasShownDevicePerformanceWarning")]
	HAS_SHOWN_DEVICE_PERFORMANCE_WARNING,
	[Description("screenshotDirectory")]
	SCREENSHOT_DIRECTORY,
	[Description("simulatingCellular")]
	SIMULATE_CELLULAR,
	[Description("assetDownloadEnabled")]
	ASSET_DOWNLOAD_ENABLED,
	[Description("updateState")]
	UPDATE_STATE,
	[Description("nativeUpdateState")]
	NATIVE_UPDATE_STATE,
	[Description("AskUnknownApps")]
	ASK_UNKNOWN_APPS,
	[Description("launchCount")]
	LAUNCH_COUNT,
	[Description("isInstallReported")]
	IS_INSTALL_REPORTED,
	[Description("firstInstallTime")]
	FIRST_INSTALL_TIME,
	[Description("updatedClientVersion")]
	UPDATED_CLIENT_VERSION,
	[Description("simulateNoInternet")]
	SIMULATE_NO_INTERNET,
	[Description("updateStopLevel")]
	UPDATE_STOP_LEVEL,
	[Description("maxDownloadSpeed")]
	MAX_DOWNLOAD_SPEED,
	[Description("streamingSpeedInGame")]
	STREAMING_SPEED_IN_GAME,
	[Description("autoConvertVirtualCurrency")]
	AUTOCONVERT_VIRTUAL_CURRENCY,
	[Description("streamerMode")]
	STREAMER_MODE,
	[Description("latestSeenShopProductList")]
	LATEST_SEEN_SHOP_PRODUCT_LIST,
	[Description("latestDisplayedShopProductList")]
	LATEST_DISPLAYED_SHOP_PRODUCT_LIST,
	[Description("rankDebug")]
	RANK_DEBUG,
	[Description("debugCursor")]
	DEBUG_CURSOR,
	[Description("crashCount")]
	CRASH_COUNT,
	[Description("exceptionCount")]
	EXCEPTION_COUNT,
	[Description("lowMemoryCount")]
	LOW_MEMORY_COUNT,
	[Description("closedWithoutCrash")]
	CLOSED_WITHOUT_CRASH,
	[Description("ExceptionHash")]
	EXCEPTION_HASH,
	[Description("LastExceptionHash")]
	LAST_EXCEPTION_HASH,
	[Description("CrashInARowCount")]
	CRASH_IN_A_ROW_COUNT,
	[Description("SameExceptionCount")]
	SAME_EXCEPTION_COUNT,
	[Description("CellPromptThreshold")]
	CELL_PROMPT_THRESHOLD,
	[Description("DownloadAllFinished")]
	DOWNLOAD_ALL_FINISHED,
	[Description("DelayedReporterStop")]
	DELAYED_REPORTER_STOP,
	[Description("ScreenshakeEnabled")]
	SCREEN_SHAKE_ENABLED,
	[Description("hudconfig")]
	HUD_CONFIG,
	[Description("hudScale")]
	HUD_SCALE,
	[Description("EnabledLogList")]
	ENABLED_LOG_LIST,
	[Description("hasSeenClipboardNotification")]
	HAS_SEEN_CLIPBOARD_NOTIFICATION,
	[Description("progTileDebug")]
	PROG_TILE_DEBUG,
	[Description("LastLoginType")]
	LAST_LOGIN_TYPE,
	[Description("TransitionToken")]
	TRANSITION_AUTH_TOKEN,
	[Description("TransitionGuestId")]
	TRANSITION_GUEST_ID,
	[Description("ANRThrottle")]
	ANR_THROTTLE,
	[Description("ANRWaitSeconds")]
	ANR_WAIT_SECONDS,
	[Description("AppRatingPopupCount")]
	APP_RATING_POPUP_COUNT,
	[Description("newestRewardedDeckId")]
	NEWEST_REWARDED_DECK_ID,
	[Description("showCreateSkipAcct")]
	SHOW_CREATE_SKIP_ACCT,
	[Description("serverOptionsVersion")]
	SERVER_OPTIONS_VERSION,
	[Description("pagemouseovers")]
	PAGE_MOUSE_OVERS,
	[Description("covermouseovers")]
	COVER_MOUSE_OVERS,
	[Description("aimode")]
	AI_MODE,
	[Description("practicetipporgress")]
	TIP_PRACTICE_PROGRESS,
	[Description("playtipprogress")]
	TIP_PLAY_PROGRESS,
	[Description("forgetipprogress")]
	TIP_FORGE_PROGRESS,
	[Description("lastChosenPreconHero")]
	LAST_PRECON_HERO_CHOSEN,
	[Description("lastChosenCustomDeck")]
	LAST_CUSTOM_DECK_CHOSEN,
	[Description("selectedAdventure")]
	SELECTED_ADVENTURE,
	[Description("selectedAdventureMode")]
	SELECTED_ADVENTURE_MODE,
	[Description("lastselectedbooster")]
	LAST_SELECTED_STORE_BOOSTER_ID,
	[Description("lastselectedadventure")]
	LAST_SELECTED_STORE_ADVENTURE_ID,
	[Description("lastselectedhero")]
	LAST_SELECTED_STORE_HERO_ID,
	[Description("seenTB")]
	LATEST_SEEN_TAVERNBRAWL_SEASON,
	[Description("seenTBScreen")]
	LATEST_SEEN_TAVERNBRAWL_SEASON_CHALKBOARD,
	[Description("seenCrazyRulesQuote")]
	TIMES_SEEN_TAVERNBRAWL_CRAZY_RULES_QUOTE,
	[Description("setRotationIntroProgress")]
	SET_ROTATION_INTRO_PROGRESS,
	[Description("timesMousedOverSwitchFormatButton")]
	TIMES_MOUSED_OVER_SWITCH_FORMAT_BUTTON,
	[Description("returningPlayerBannerSeen")]
	RETURNING_PLAYER_BANNER_SEEN,
	[Description("seenTBSessionLimit")]
	LATEST_SEEN_TAVERNBRAWL_SESSION_LIMIT,
	[Description("lastTavernJoined")]
	LAST_TAVERN_JOINED,
	[Description("seenFSGB")]
	LATEST_SEEN_FIRESIDEBRAWL_SEASON,
	[Description("seenFSGBScreen")]
	LATEST_SEEN_FIRESIDEBRAWL_SEASON_CHALKBOARD,
	[Description("seenScheduledDoubleGoldVO")]
	LATEST_SEEN_SCHEDULED_DOUBLE_GOLD_VO,
	[Description("seenScheduledAllPopupsShownVO")]
	LATEST_SEEN_SCHEDULED_ALL_POPUPS_SHOWN_VO,
	[Description("seenScheduledEnteredArenaDraftVO")]
	LATEST_SEEN_SCHEDULED_ENTERED_ARENA_DRAFT,
	[Description("seenScheduledLoginFlowComplete")]
	LATEST_SEEN_SCHEDULED_LOGIN_FLOW_COMPLETE,
	[Description("seenWelcomeQuestDialog")]
	LATEST_SEEN_WELCOME_QUEST_DIALOG,
	[Description("seenCurrencyChangeMessageForVersion")]
	LATEST_SEEN_CURRENCY_CHANGED_VERSION,
	[Description("seenScheduledWelcomeQuestVO")]
	LATEST_SEEN_SCHEDULED_WELCOME_QUEST_SHOWN_VO,
	[Description("seenScheduledGenericRewardShownVO")]
	LATEST_SEEN_SCHEDULED_GENERIC_REWARD_SHOWN_VO,
	[Description("seenScheduledArenaRewardShownVO")]
	LATEST_SEEN_SCHEDULED_ARENA_REWARD_SHOWN_VO,
	[Description("lastSelectedStorePackType")]
	LAST_SELECTED_STORE_PACK_TYPE,
	[Description("whizbangPopupCounter")]
	WHIZBANG_POPUP_COUNTER,
	[Description("setRotationIntroProgressNewPlayer")]
	SET_ROTATION_INTRO_PROGRESS_NEW_PLAYER,
	[Description("formatType")]
	FORMAT_TYPE,
	[Description("formatTypeLastPlayed")]
	FORMAT_TYPE_LAST_PLAYED,
	[Description("hasclickedtournament")]
	HAS_CLICKED_TOURNAMENT,
	[Description("hasopenedbooster")]
	HAS_OPENED_BOOSTER,
	[Description("hasseentournament")]
	HAS_SEEN_TOURNAMENT,
	[Description("hasseencollectionmanager")]
	HAS_SEEN_COLLECTIONMANAGER,
	[Description("justfinishedtutorial")]
	JUST_FINISHED_TUTORIAL,
	[Description("showadvancedcollectionmanager")]
	SHOW_ADVANCED_COLLECTIONMANAGER,
	[Description("hasseenpracticetray")]
	HAS_SEEN_PRACTICE_TRAY,
	[Description("firstHubVisitPastTutorial")]
	HAS_SEEN_HUB,
	[Description("firstdeckcomplete")]
	HAS_FINISHED_A_DECK,
	[Description("hasseenforge")]
	HAS_SEEN_FORGE,
	[Description("hasseenforgeherochoice")]
	HAS_SEEN_FORGE_HERO_CHOICE,
	[Description("hasseenforgecardchoice")]
	HAS_SEEN_FORGE_CARD_CHOICE,
	[Description("hasseenforgecardchoice2")]
	HAS_SEEN_FORGE_CARD_CHOICE2,
	[Description("hasseenforgeplaymode")]
	HAS_SEEN_FORGE_PLAY_MODE,
	[Description("hasseenforge1win")]
	HAS_SEEN_FORGE_1WIN,
	[Description("hasseenforge2loss")]
	HAS_SEEN_FORGE_2LOSS,
	[Description("hasseenforgeretire")]
	HAS_SEEN_FORGE_RETIRE,
	[Description("hasseenmulligan")]
	HAS_SEEN_MULLIGAN,
	[Description("hasSeenExpertAI")]
	HAS_SEEN_EXPERT_AI,
	[Description("hasSeenExpertAIUnlock")]
	HAS_SEEN_EXPERT_AI_UNLOCK,
	[Description("hasseendeckhelper")]
	HAS_SEEN_DECK_HELPER,
	[Description("hasSeenPackOpening")]
	HAS_SEEN_PACK_OPENING,
	[Description("hasSeenPracticeMode")]
	HAS_SEEN_PRACTICE_MODE,
	[Description("hasSeenCustomDeckPicker")]
	HAS_SEEN_CUSTOM_DECK_PICKER,
	[Description("hasSeenAllBasicClassCardsComplete")]
	HAS_SEEN_ALL_BASIC_CLASS_CARDS_COMPLETE,
	[Description("hasBeenNudgedToCM")]
	HAS_BEEN_NUDGED_TO_CM,
	[Description("hasAddedCardsToDeck")]
	HAS_ADDED_CARDS_TO_DECK,
	[Description("tipCraftingUnlocked")]
	TIP_CRAFTING_UNLOCKED,
	[Description("hasPlayedExpertAI")]
	HAS_PLAYED_EXPERT_AI,
	[Description("hasDisenchanted")]
	HAS_DISENCHANTED,
	[Description("hasSeenShowAllCardsReminder")]
	HAS_SEEN_SHOW_ALL_CARDS_REMINDER,
	[Description("hasSeenCraftingInstruction")]
	HAS_SEEN_CRAFTING_INSTRUCTION,
	[Description("hasCrafted")]
	HAS_CRAFTED,
	[Description("inRankedPlayMode")]
	IN_RANKED_PLAY_MODE,
	[Description("hasSeenTheCoin")]
	HAS_SEEN_THE_COIN,
	[Description("hasseen100goldReminder")]
	HAS_SEEN_100g_REMINDER,
	[Description("hasSeenGoldQtyInstruction")]
	HAS_SEEN_GOLD_QTY_INSTRUCTION,
	[Description("hasSeenLevel3")]
	HAS_SEEN_LEVEL_3,
	[Description("hasLostInArena")]
	HAS_LOST_IN_ARENA,
	[Description("hasRunOutOfQuests")]
	HAS_RUN_OUT_OF_QUESTS,
	[Description("hasAckedArenaRewards")]
	HAS_ACKED_ARENA_REWARDS,
	[Description("hasSeenStealthTaunter")]
	HAS_SEEN_STEALTH_TAUNTER,
	[Description("friendslistrequestsectionhide")]
	FRIENDS_LIST_REQUEST_SECTION_HIDE,
	[Description("friendslistcurrentgamesectionhide")]
	FRIENDS_LIST_CURRENTGAME_SECTION_HIDE,
	[Description("friendslistfriendsectionhide")]
	FRIENDS_LIST_FRIEND_SECTION_HIDE,
	[Description("friendslistnearbysectionhide")]
	FRIENDS_LIST_NEARBYPLAYER_SECTION_HIDE,
	[Description("friendslistrecruitsectionhide")]
	FRIENDS_LIST_RECRUIT_SECTION_HIDE,
	[Description("hasSeenHeroicWarning")]
	HAS_SEEN_HEROIC_WARNING,
	[Description("hasSeenNaxx")]
	HAS_SEEN_NAXX,
	[Description("hasEnteredNaxx")]
	HAS_ENTERED_NAXX,
	[Description("hasSeenNaxxClassChallenge")]
	HAS_SEEN_NAXX_CLASS_CHALLENGE,
	[Description("bundleJustPurchaseInHub")]
	BUNDLE_JUST_PURCHASE_IN_HUB,
	[Description("hasPlayedNaxx")]
	HAS_PLAYED_NAXX,
	[Description("spectatoropenjoin")]
	SPECTATOR_OPEN_JOIN,
	[Description("hasstartedadeck")]
	HAS_STARTED_A_DECK,
	[Description("hasseencollectionmanagerafterpractice")]
	HAS_SEEN_COLLECTIONMANAGER_AFTER_PRACTICE,
	[Description("hasSeenBRM")]
	HAS_SEEN_BRM,
	[Description("hasSeenLOE")]
	HAS_SEEN_LOE,
	[Description("hasClickedManaTab")]
	HAS_CLICKED_MANA_TAB,
	[Description("hasseenforgemaxwin")]
	HAS_SEEN_FORGE_MAX_WIN,
	[Description("hasheardtgtpackvo")]
	DEPRECATED_HAS_HEARD_TGT_PACK_VO,
	[Description("hasseenloestaffdisappear")]
	HAS_SEEN_LOE_STAFF_DISAPPEAR,
	[Description("hasseenloestaffreappear")]
	HAS_SEEN_LOE_STAFF_REAPPEAR,
	[Description("hasSeenUnlockAllHeroesTransition")]
	HAS_SEEN_UNLOCK_ALL_HEROES_TRANSITION,
	[Description("createdFirstDeckForClass")]
	SKIP_DECK_TEMPLATE_PAGE_FOR_CLASS_FLAGS,
	[Description("hasSeenDeckTemplateScreen")]
	HAS_SEEN_DECK_TEMPLATE_SCREEN,
	[Description("hasClickedDeckTemplateReplace")]
	HAS_CLICKED_DECK_TEMPLATE_REPLACE,
	[Description("hasSeenDeckTemplateGhostCard")]
	HAS_SEEN_DECK_TEMPLATE_GHOST_CARD,
	[Description("hasRemovedCardFromDeck")]
	HAS_REMOVED_CARD_FROM_DECK,
	[Description("hasSeenDeleteDeckReminder")]
	DEPRECATED_HAS_SEEN_DELETE_DECK_REMINDER,
	[Description("hasClickedCollectionButtonForNewCard")]
	HAS_CLICKED_COLLECTION_BUTTON_FOR_NEW_CARD,
	[Description("hasClickedCollectionButtonForNewDeck")]
	HAS_CLICKED_COLLECTION_BUTTON_FOR_NEW_DECK,
	[Description("hasSeenWildModeVO")]
	HAS_SEEN_WILD_MODE_VO,
	[Description("hasSeenStandardModeTutorial")]
	HAS_SEEN_STANDARD_MODE_TUTORIAL,
	[Description("needsToMakeStandardDeck")]
	NEEDS_TO_MAKE_STANDARD_DECK,
	[Description("hasSeenInvalidRotatedCard")]
	HAS_SEEN_INVALID_ROTATED_CARD,
	[Description("showSwitchToWildOnPlayScreen")]
	SHOW_SWITCH_TO_WILD_ON_PLAY_SCREEN,
	[Description("showSwitchToWildOnCreateDeck")]
	SHOW_SWITCH_TO_WILD_ON_CREATE_DECK,
	[Description("showWildDisclaimerPopupOnCreateDeck")]
	SHOW_WILD_DISCLAIMER_POPUP_ON_CREATE_DECK,
	[Description("hasSeenBasicDeckWarning")]
	HAS_SEEN_BASIC_DECK_WARNING,
	[Description("glowCollectionButtonAfterSetRotation")]
	GLOW_COLLECTION_BUTTON_AFTER_SET_ROTATION,
	[Description("hasSeenSetFilterTutorial")]
	HAS_SEEN_SET_FILTER_TUTORIAL,
	[Description("hasSeenRAF")]
	HAS_SEEN_RAF,
	[Description("hasSeenRAFRecruitURL")]
	HAS_SEEN_RAF_RECRUIT_URL,
	[Description("hasSeenKara")]
	HAS_SEEN_KARA,
	[Description("hasseenheroicbrawl")]
	HAS_SEEN_HEROIC_BRAWL,
	[Description("hasHeardReturningPlayerWelcomeBackVO")]
	HAS_HEARD_RETURNING_PLAYER_WELCOME_BACK_VO,
	[Description("hadItemThatWillBeRotatedInUpcomingEvent")]
	DEPRECATED_HAD_ITEM_THAT_WILL_BE_ROTATED_IN_UPCOMING_EVENT,
	[Description("shouldAutoCheckInToFiresideGatherings")]
	SHOULD_AUTO_CHECK_IN_TO_FIRESIDE_GATHERINGS,
	[Description("hasClickedFiresideBrawlButton")]
	HAS_CLICKED_FIRESIDE_BRAWL_BUTTON,
	[Description("hasClickedFiresideGatheringsButton")]
	HAS_CLICKED_FIRESIDE_GATHERINGS_BUTTON,
	[Description("hasInitiatedFSGScan")]
	HAS_INITIATED_FIRESIDE_GATHERING_SCAN,
	[Description("hasDisabledPremiumsThisDraft")]
	HAS_DISABLED_PREMIUMS_THIS_DRAFT,
	[Description("hasSeenFreeArenaWinDialogThisDraft")]
	HAS_SEEN_FREE_ARENA_WIN_DIALOG_THIS_DRAFT,
	[Description("hasSeenICC")]
	HAS_SEEN_ICC,
	[Description("seenArenaSeasonStarting")]
	LATEST_SEEN_ARENA_SEASON_STARTING,
	[Description("seenArenaSeasonEnding")]
	LATEST_SEEN_ARENA_SEASON_ENDING,
	[Description("hasSeenLOOT")]
	HAS_SEEN_LOOT,
	[Description("hasSeenLatestDungeonRunComplete")]
	HAS_SEEN_LATEST_DUNGEON_RUN_COMPLETE,
	[Description("hasSeenLOOTCharacterSelectVO")]
	HAS_SEEN_LOOT_CHARACTER_SELECT_VO,
	[Description("hasSeenLOOTWelcomeBannerVO")]
	HAS_SEEN_LOOT_WELCOME_BANNER_VO,
	[Description("hasSeenLOOTBossFlip1VO")]
	HAS_SEEN_LOOT_BOSS_FLIP_1_VO,
	[Description("hasSeenLOOTBossFlip2VO")]
	HAS_SEEN_LOOT_BOSS_FLIP_2_VO,
	[Description("hasSeenLOOTBossFlip3VO")]
	HAS_SEEN_LOOT_BOSS_FLIP_3_VO,
	[Description("hasSeenLOOTOfferTreasure1VO")]
	HAS_SEEN_LOOT_OFFER_TREASURE_1_VO,
	[Description("hasSeenLOOTOfferLootPacks1VO")]
	HAS_SEEN_LOOT_OFFER_LOOT_PACKS_1_VO,
	[Description("hasSeenLOOTOfferLootPacks2VO")]
	HAS_SEEN_LOOT_OFFER_LOOT_PACKS_2_VO,
	[Description("hasJustSeenLOOTNoTakeCandleVO")]
	HAS_JUST_SEEN_LOOT_NO_TAKE_CANDLE_VO,
	[Description("hasSeenLOOTInGameWinVO")]
	HAS_SEEN_LOOT_IN_GAME_WIN_VO,
	[Description("hasSeenLOOTInGameLoseVO")]
	HAS_SEEN_LOOT_IN_GAME_LOSE_VO,
	[Description("hasSeenLOOTInGameMulligan1VO")]
	HAS_SEEN_LOOT_IN_GAME_MULLIGAN_1_VO,
	[Description("hasSeenLOOTInGameMulligan2VO")]
	HAS_SEEN_LOOT_IN_GAME_MULLIGAN_2_VO,
	[Description("hasSeenLOOTCompleteAllClassesVO")]
	HAS_SEEN_LOOT_COMPLETE_ALL_CLASSES_VO,
	[Description("hasSeenLOOTBossHeroPower")]
	HAS_SEEN_LOOT_BOSS_HERO_POWER,
	[Description("hasSeenLOOTInGameLose2VO")]
	HAS_SEEN_LOOT_IN_GAME_LOSE_2_VO,
	[Description("hasSeenRankRevampEndOfGameWinsRequired")]
	HAS_SEEN_RANK_REVAMP_END_OF_GAME_WINS_REQUIRED,
	[Description("hasSeenGILBonusChallenge")]
	HAS_SEEN_GIL_BONUS_CHALLENGE,
	[Description("hasSeenPlayedTess")]
	HAS_SEEN_PLAYED_TESS,
	[Description("hasSeenPlayedDarius")]
	HAS_SEEN_PLAYED_DARIUS,
	[Description("hasSeenPlayedShaw")]
	HAS_SEEN_PLAYED_SHAW,
	[Description("hasSeenPlayedToki")]
	HAS_SEEN_PLAYED_TOKI,
	[Description("hasSeenBattlegroundsBoxButton")]
	HAS_SEEN_BATTLEGROUNDS_BOX_BUTTON,
	[Description("hasSeenClassicModeVO")]
	HAS_SEEN_CLASSIC_MODE_VO,
	[Description("hasAcceptedPrivacyPolicyAndEULA")]
	HAS_ACCEPTED_PRIVACY_POLICY_AND_EULA
}
