public enum ScheduledCharacterDialogEvent
{
	INVALID,
	DOUBLE_GOLD_QUEST_GRANTED,
	ALL_POPUPS_SHOWN,
	ENTERED_ARENA_DRAFT,
	LOGIN_FLOW_COMPLETE,
	WELCOME_QUESTS_SHOWN,
	GENERIC_REWARD_SHOWN,
	ARENA_REWARD_SHOWN,
	ENTERED_BATTLEGROUNDS,
	ENTERED_TAVERN_BRAWL,
	PURCHASED_BUNDLE
}
