public enum ShopType
{
	GENERAL_STORE,
	ARENA_STORE,
	ADVENTURE_STORE,
	TAVERN_BRAWL_STORE,
	ADVENTURE_STORE_WING_PURCHASE_WIDGET,
	ADVENTURE_STORE_FULL_PURCHASE_WIDGET,
	DUELS_STORE,
	CARD_BACK_STORE,
	HERO_SKIN_STORE
}
