public enum ShopAvailabilityError
{
	UNKNOWN,
	FIRST_NOTICES_NOT_PROCESSED,
	STORE_FEATURE_DISABLED,
	BATTLEPAY_UNAVAILABLE,
	BATTLEPAY_CONFIG_NOT_LOADED,
	NO_PRODUCTS_FOR_SALE,
	NOT_LOGGED_IN,
	CHECKOUT_INITIALIZING,
	CHECKOUT_UNAVAILABLE,
	CHECKOUT_NOT_ENABLED,
	TRANSACTION_STATUS_UNKNOWN,
	NO_ERROR
}
