public enum TagVisualActorCondition
{
	ALWAYS = 0,
	AND = 1,
	OR = 2,
	DOES_SPELL_HAVE_STATE = 3,
	DOES_TAG_HAVE_VALUE = 4,
	IS_ENRAGED = 5,
	IS_ASLEEP = 6,
	IS_FRIENDLY = 7,
	IS_MOUSED_OVER = 8,
	IS_ENCHANTMENT = 9,
	IS_DISABLED_HERO_POWER = 10,
	IS_FROM_SHOW_ENTITY = 11,
	IS_REAL_TIME_DORMANT = 0x10,
	IS_AI_CONTROLLER = 17,
	IS_FROM_TAG_CHANGE = 18,
	IS_VALID_OPTION = 20,
	SHOULD_SHOW_IMMUNE_VISUALS = 12,
	CAN_SHOW_ACTOR_VISUALS = 13,
	ATTACHED_CARD_CAN_SHOW_ACTOR_VISUALS = 14,
	SHOULD_USE_TECH_LEVEL_MANA_GEM = 0xF,
	SHOULD_USE_COIN_ON_ENEMY_MINIONS = 19
}
