namespace PegasusUtil
{
	public enum ProductType
	{
		PRODUCT_TYPE_UNKNOWN,
		PRODUCT_TYPE_BOOSTER,
		PRODUCT_TYPE_DRAFT,
		PRODUCT_TYPE_NAXX,
		PRODUCT_TYPE_BRM,
		PRODUCT_TYPE_CARD_BACK,
		PRODUCT_TYPE_HERO,
		PRODUCT_TYPE_LOE,
		PRODUCT_TYPE_WING,
		PRODUCT_TYPE_RANDOM_CARD,
		PRODUCT_TYPE_HIDDEN_LICENSE,
		PRODUCT_TYPE_TAVERN_BRAWL_TICKET,
		PRODUCT_TYPE_CURRENCY,
		PRODUCT_TYPE_FIXED_LICENSE,
		PRODUCT_TYPE_BATTLEGROUNDS_BONUS,
		PRODUCT_TYPE_PROGRESSION_BONUS,
		PRODUCT_TYPE_MINI_SET,
		PRODUCT_TYPE_SELLABLE_DECK
	}
}
